import { DemoScenario } from '../types';

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 'aarav_scam',
    name: "Aarav's Remote Desk Scam (Tech Support Scam)",
    tagline: 'High Risk / Remote Screen Sharing Detected',
    description: 'Elderly or distracted customer guided over screen-sharing to drain savings to an unverified mule account.',
    expectedInterface: 'emergency',
    riskBand: 'emergency',
    trustScore: 14,
    recipient: 'Cyber Node Mumbai Escrow (Rajesh Verma)',
    amount: 48500.00,
    signals: {
      screenSharingActive: true,
      unusualTimeOfDay: true,
      newRecipient: true,
      highVelocity: true,
      geoAnomaly: true,
      rapidAmountEscalation: true,
      deviceBiometricBypass: true,
    },
    naturalLanguageSummary:
      'Our security model immediately halted this transfer because an active remote-desktop session was running concurrently with a critical account drain to an unverified recipient. This precisely matches remote-access impersonation scams. Your funds remain 100% safe in your account.',
    layer7Warnings: [
      'Active screen-sharing or remote desktop session detected during transaction authorization',
      'Recipient account/IFSC was generated < 48 hours ago with zero shared transaction history',
      'Transaction velocity escalated from typical ₹500 balance transfers to ₹48,500 in a single window',
      'Geographic IP telemetry deviates > 2,400 km from recognized residential profile',
    ],
  },
  {
    id: 'legitimate_large',
    name: 'Legitimate Large Purchase',
    tagline: 'Moderate Confidence / Step-Up OTP Verification',
    description: 'User purchasing home furniture materials exceeding their customary single-purchase limit.',
    expectedInterface: 'normal_with_extra',
    riskBand: 'slightly_suspicious',
    trustScore: 76,
    recipient: 'FabIndia Crafts Pvt Ltd',
    amount: 12500.00,
    signals: {
      screenSharingActive: false,
      unusualTimeOfDay: false,
      newRecipient: true,
      highVelocity: false,
      geoAnomaly: false,
      rapidAmountEscalation: true,
    },
    naturalLanguageSummary:
      'This transaction was initiated from your recognized hardware device on your home network. Because the payment amount is above your 30-day single transfer average, a quick one-time security passkey is required.',
    layer7Warnings: [
      'Transaction amount (₹12,500.00) exceeds habitual discretionary purchase threshold by 3.2x',
      'First-time transfer to recipient merchant, but merchant has verified commercial GST accreditation',
    ],
  },
  {
    id: 'routine_rent',
    name: 'Routine Monthly Rent',
    tagline: 'High Trust / Frictionless Approval',
    description: 'Recurring monthly apartment rental payment to an existing recognized housing society account.',
    expectedInterface: 'normal',
    riskBand: 'trusted',
    trustScore: 98,
    recipient: 'Godrej Greens Residency',
    amount: 18500.00,
    signals: {
      screenSharingActive: false,
      unusualTimeOfDay: false,
      newRecipient: false,
      highVelocity: false,
      geoAnomaly: false,
      rapidAmountEscalation: false,
    },
    naturalLanguageSummary:
      'Regular scheduled recurring recipient. Authorized on your primary trusted smartphone with biometric validation. Zero risk indicators present.',
    layer7Warnings: [],
  },
  {
    id: 'latenight_screenshare',
    name: 'Late-Night Screen Sharing Transfer',
    tagline: 'Suspicious / Simplified High-Clarity Warning',
    description: 'Transfer initiated at 3 AM while screen-sharing app is streaming in background.',
    expectedInterface: 'simplified',
    riskBand: 'suspicious',
    trustScore: 42,
    recipient: 'WazirVault Liquidations',
    amount: 9200.00,
    signals: {
      screenSharingActive: true,
      unusualTimeOfDay: true,
      newRecipient: true,
      highVelocity: false,
      geoAnomaly: false,
      rapidAmountEscalation: false,
    },
    naturalLanguageSummary:
      'We paused this transfer because a screen-mirroring broadcast is currently streaming on your phone at an unusual late-night hour. We have simplified this screen so you can verify who is viewing your device before funds leave your balance.',
    layer7Warnings: [
      'Screen capture or cast stream active on local device during payment entry',
      'Transaction initiated at 03:22 AM local time (outside habitual active hours)',
      'Destination account categorized as instant cryptocurrency liquidation portal',
    ],
  },
  {
    id: 'unusual_device_geo',
    name: 'Unusual Device & New Location',
    tagline: 'Review Pending / Identity Verification Required',
    description: 'Transfer submitted from an unrecognized browser fingerprint through an overseas VPN node.',
    expectedInterface: 'review_pending',
    riskBand: 'review_pending',
    trustScore: 54,
    recipient: 'Kalyan Escrow Clearing Hub',
    amount: 21000.00,
    signals: {
      screenSharingActive: false,
      unusualTimeOfDay: false,
      newRecipient: true,
      highVelocity: true,
      geoAnomaly: true,
      rapidAmountEscalation: false,
    },
    naturalLanguageSummary:
      'This transaction was flagged for manual review because it originated from a brand-new device signature connecting through an anonymous proxy. Your transfer is paused safely in escrow while we verify your identity.',
    layer7Warnings: [
      'Hardware canvas fingerprint does not match any registered user credentials',
      'Inbound connection routed through an anonymous exit node or high-risk datacenter subnet',
      'Simultaneous login active from two geographically impossible physical coordinates',
    ],
  },
];
